### ISSUE TITLE
mental or behavioural disorder/brain disease classification

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#117]
@gkos-bio commented on [Tue Mar 28 2017](https://github.com/opentargets/platform_semantic/issues/5)

mental or behavioural disorder is classified under other disease for some reason.
It should be at the same level as the other main categories
https://www.targetvalidation.org/disease/EFO_0000677

**Comment by ElaineMcA** [comment]
Check if resolved within EFO 3.

**Comment by afaulconbridge** [comment]
We do some re-arrangement of high level EFO diseases within OpenTargets, to make the high levels more presentable than the default organisation within EFO (see https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000408 ). So I think this is probably something to look at on our side, rather than within EFO 3 (though the relevant bits of code will need updating for EFO 3 anyway, but that's probably a separate, and bigger, issue).

**Comment by iandunham** [comment]
Simon Jupp is aware of our structure - the TAs, and would be willing to think about getting this cleaner for us

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #92](https://github.com/opentargets/platform/issues/92) via [**ZenHub**](https://www.zenhub.com/)
