### ISSUE TITLE
number of total targets in the results page of batch search

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#127]
@deniseOme commented on [Mon Oct 23 2017](https://github.com/opentargets/platform_issues/issues/38)

Can the total numbers of targets be reported for each disease in the results page of the batch search? This number would be in brackets.

<img width="243" alt="screen shot 2017-10-23 at 17 37 47" src="https://user-images.githubusercontent.com/6472381/31901203-ac38e1e8-b818-11e7-81d6-862e9cd099ee.png">

As per June 2017, we would have:

Crohn's disease (3426).

**Comment by andrewhercules** [comment]
Triage notes:

- Due to current layout of Diseases Associated table and truncation of disease name, this isn't a feasible request 
- Concerned that adding a number would cause more user confusion and then would need to add additional columns to explain relevance of that number in relation to the targets they entered in the batch search

**Comment by andrewhercules** [comment]
Issue closed as per triage notes above
