### ISSUE TITLE
Can I search for a blog post on ghost? Add search to the frontend of ghost.

### ISSUE THREAD

**Issue by deniseOme** [opentargets/roadmap#142]
## Description
* [ ] **WHY - What is the problem this feature would answer?**  

Our blog has now several posts. These are paginated and it's difficult to find a given post I look for. We do have an index (menu) but it does not list the individual posts.

We need to make easier for users to find our blog content. Things that need to be searchable are post titles and key words for example but could be extended to others e.g. authors, metadata

This shortcoming was highlighted at Takeda by a user. He wanted to search for a post and told there should be a way to do so.

* [ ] **HOW are we going to solve the problem?**  
According to @elipapa this functionality can be added (e.g. https://mrvautin.com/how-to-add-search-functionality-to-your-ghost-blog/)

**Comment by andrewhercules** [comment]
Issue closed due to issues with the hack described in the link - it can be glitchy and only searches titles, not content. Also, the current blog layout allows for continual scrolling and loading of new content - similar to how many apps work - so a user will be able to see all content without having to try and construct a search query based on how we might title a post. 

Also, my recommendation is that we make better use of the navigation menu by analysing the Google Analytics data to determine which posts are most popular. We currently add tags to all posts and once we know which posts are the most popular, we can create one-click links to these "search results".
